# General
site_name: Shippable Docs
repo_url: https://github.com/Shippable/docs

# Paths
docs_dir: sources
# this is breaking the mkdocs build.
# commentimg this to get docs working with default theme
#theme_dir: theme/saas

#detect broken links and break the build
strict: true

#Google Analytics
google_analytics: ['UA-50610279-1', 'auto']
